//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LargeShipPatcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LargeShipPatcher.Configs", typeof(Configs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gModSettings enableLargeShips=&quot;true&quot; shipPoints=&quot;14&quot; systemPointsPerShipPoint=&quot;4&quot; sectorSize=&quot;10&quot; /&gt;.
        /// </summary>
        internal static string LargeShipPatcher {
            get {
                return ResourceManager.GetString("LargeShipPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## LargeShipPatcher v0.10.0-4
        ///
        ///### A Space Haven mod
        ///
        ///#### Features
        ///
        ///- Allow ships of size 3x2, 2x3 and 3x3 to be build
        ///- Increase the available ship points from 8 to 14
        ///- Increase sector size from 8x8 to 10x10
        ///- Allow changing the amount of system points per ship point
        ///- Features can be tweaked by editing the `LargeShipPatcher.xml` file
        ///- OSX/Linux support (**untested**)
        ///
        ///#### Instructions
        ///- Copy the patcher in the same folder as `spacehaven.jar`
        ///- Execute it as administrator (sudo on linux) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMe {
            get {
                return ResourceManager.GetString("ReadMe", resourceCulture);
            }
        }
    }
}
